[Task][Fe] Create Secure Store Library
Youngs-Milling-Software-Devs/Attendance-App pull request #19
Opened 2024-03-27 09:32 UTC by jemian868

### [Github Task Link]
[[Task][Fe] Create Secure Store Library](https://github.com/orgs/Youngs-Milling-Software-Devs/projects/15/views/1?pane=issue&itemId=57825523)

### [Commands]
`npm i`
`npm run start`

### [Pre-Conditions]

None

### [Expected Output]

None

### [Notes]

None

### [Screenshots]

None

2024-03-27 09:40 UTC, alOletres requested changes

2024-03-27 09:40 UTC, alOletres commented on src/lib/SecureStore.ts
> +export const setSecureValue = async (key: string, value: string) => {
```suggestion
type SecureKey = "accessToken" |  "refreshToken"
export const setSecureValue = async (key: SecureKey, value: string) => {
```

2024-03-27 09:40 UTC, alOletres commented on src/screens/public/login/index.tsx
> +          <Button
```suggestion
          delete
```

2024-03-27 09:40 UTC, alOletres commented on src/screens/public/login/index.tsx
> +  const { navigation, control, handleSubmit, handleFormSubmit, sample } =
```suggestion
omit sample property
```

2024-03-27 09:40 UTC, alOletres commented on src/state/reducers/hrmis/loginSlice.ts
> +            setSecureValue("access", data.access);
```suggestion
            setSecureValue("accessToken", data.access);
```

2024-04-08 01:49 UTC, alOletres requested changes

2024-04-08 01:49 UTC, alOletres commented on src/lib/SecureStore.ts
> +export const getSecureValue = async (key: string) => {
```suggestion
export const getSecureValue = async (key: SecureKey) => {
```

2024-04-08 01:49 UTC, alOletres commented on src/screens/public/login/hook.ts
> +    console.log("reduxResponse", isSuccess, message);
```suggestion
delete console.log
```

2024-04-08 01:51 UTC, merged

2026-03-19 11:18 UTC, LodiAniez commented
haha ang commands